Update leaks.rb
Requiring `rspec/files` without requiring `rspec` raises an error:
```
irb(main):001:0> require 'rspec/files'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-files-1.1.1/lib/rspec/files/leaks.rb:39:in `<module:Files>': undefined method `shared_context' for RSpec:Module (NoMethodError)

                RSpec.shared_context Leaks do
                     ^^^^^^^^^^^^^^^
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-files-1.1.1/lib/rspec/files/leaks.rb:22:in `<module:RSpec>'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-files-1.1.1/lib/rspec/files/leaks.rb:21:in `<top (required)>'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-files-1.1.1/lib/rspec/files.rb:22:in `require_relative'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-files-1.1.1/lib/rspec/files.rb:22:in `<top (required)>'
        from (irb):1:in `require'
        from (irb):1:in `<main>'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /home/user/.asdf/installs/ruby/3.1.2/bin/irb:25:in `load'
        from /home/user/.asdf/installs/ruby/3.1.2/bin/irb:25:in `<top (required)>'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `load'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:23:in `run'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/cli.rb:483:in `exec'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        ... 8 levels...
```